services:
  extractor:
    build: .
    tty: true
  db: 
    container_name: github_data_pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $PG_USERNAME
      POSTGRES_PASSWORD: $PG_PASSWORD
      PGDATA: /var/lib/postgresql/data
    ports: 
      - $PG_PORT:$PG_PORT